### ISSUE TITLE
Support beta version

### ISSUE THREAD

**Issue by grappler** [Rarst/release-belt#11]
Currently the regex is unable to parse beta version.

Examples: `2.0-beta.1` and `2.0-beta2`

It may be good to support RC too. e.g. `2.0.0-rc.1`

**Comment by grappler** [comment]
A possible regex https://regex101.com/r/dL9yN2/1

**Comment by Rarst** [comment]
Names that fail in tests with suggested regex:
- `p3-profiler.1.5.3.6.zip`
- `wp-retina-2x.2.4.0.zip`

Seems to have an issue with digit in name.

Also simpler version seems to fail too:
- `wp-lightbox-2.zip`

**Comment by Rarst** [comment]
I had borrowed regex for modifiers from `composer/semver` (MIT). That got all your cases going, except numbered RCs (which should be rare enough).

**Comment by grappler** [comment]
I just realised that number RCs work if it is written in capitals. This for example `gravityformsgutenberg_1.0-RC-1.1.zip` works.

**Comment by Rarst** [comment]
Yeah, that seems consistent with regex, must have missed it at the time, sorry. :)
