### ISSUE TITLE
HTTP authentiction

### ISSUE THREAD

**Issue by grappler** [Rarst/release-belt#13]
It would be nice to support the http authentication that composer supports. :grinning: 

https://getcomposer.org/doc/articles/http-basic-authentication.md
http://oliversmith.io/technology/2012/05/07/http-basic-auth-in-silex/

**Comment by Rarst** [comment]
Getting to it... :)

Meanwhile if you add HTTP authentication on web server level it was reported to work fine with Release Belt.

**Comment by grappler** [comment]
Great stuff, I can confirm that it works too. :D

**Comment by Rarst** [comment]
HTTP authentication implemented and documented in readme https://github.com/Rarst/release-belt#authentication
