### ISSUE TITLE
mustache/silex-provider (dev-silex-v2 04703db)

### ISSUE THREAD

**Issue by abumalick** [Rarst/release-belt#14]
Hello,
I think you deleted your silex-provider fork because [pull request](https://github.com/bobthecow/mustache-silex-provider/commit/a77353609db9400fe9f1cb1ce8c300cedf095ed6) have been merged on bobthecow/mustache-silex-provider .

I got an error installing release-belt, I think we should remove `dev-silex-v2 04703db` from `composer.json` and stick to `^2.0.0` from original repository, shouldn't we ?
Thanks for your work, it's really useful

**Comment by Rarst** [comment]
Cheers, missed to update it here. :)

**Comment by abumalick** [comment]
Thanks
