### ISSUE TITLE
Boilerplate: auth.json shouldn't include the scheme for the repo

### ISSUE THREAD

**Issue by ocean90** [Rarst/release-belt#15]
The [boilerplate for the auth.json](https://github.com/Rarst/release-belt/blob/bf50ca91c208a70782463e832fe979480082479a/php/Controller.php#L46) includes the scheme for the current repo but it should only be the hostname:

> The file should contain a set of hostnames followed each with their own username/password pairs, for example

https://getcomposer.org/doc/articles/http-basic-authentication.md

**Comment by Rarst** [comment]
Fixed, cheers! Sorry it took a while, hadn’t touched code things much. :)
