### ISSUE TITLE
packages.json file could not be downloaded

### ISSUE THREAD

**Issue by mawiswiss** [Rarst/release-belt#16]
I got the following error when running `composer update` on my local machine:
```
[Composer\Downloader\TransportException] The "http://composer.miux.ch/packages.json" file could not be downloaded (HTTP/1.1 404 Not Found)
```
Is there a package.json needed? Packagist.org does have one.
Maybe this could also be triggered based on the non usage of HTTPS. What do you think?

**Comment by Rarst** [comment]
`packages.json` is generated by the application dynamically, that's the "magic" and main function here.

Had you configured your web server to load `index.php` for this location, as per installation instructions? https://github.com/Rarst/release-belt#installation

**Comment by mawiswiss** [comment]
Well, you're right. I didn't paid enough attention to this detail, because I thought it's default.
