### ISSUE TITLE
Per–user permissions rules for packages

### ISSUE THREAD

**Issue by Rarst** [Rarst/release-belt#23]
At the moment every user has access to every package in the repository. As usage scenarios get more complicated it makes sense that more granular permissions can be needed.

My first thought on logic was whitelist with scenarios that are friendly to filesystem–centric mechanics:

- all of a type `wordpress-plugin/*`
- all of a vendor `vendor-name/*`
- all versions of a package `package-name*`
- arbitrary combination of the above

However I imagine there would be scenarios that this doesn't fit conveniently. Say user A needs 99/100 packages and user B needs 1/100. Whitelist is convenient to configure for latter, but not former.

From the implementation point of view I'd love if I could get this done just by throwing filters on Finder instance. However if it gets any elaborate I would likely need to introduce intermediary collection of releases for it.

Another point of consideration is anonymous access. Currently enabling _any_ users disables public access completely. With more granular permissions it would make sense that anonymous user could be also granted access to specific packages.

Overall I'll note that my priority for authentication remains the same — keep it as clear and simple as possible. In my opinion anything elaborate would be realm of custom in–house solutions, probably with hard separation by _multiple_ release dirs dynamically.

**Comment by Rarst** [comment]
Hm, I suppose with HTTP authentication server needs to proactively ask for it, so separating out anonymous user won't work too well.

**Comment by Rarst** [comment]
@grappler I’ve pushed new permission system to master, give it a spin if you have a sec. :) Will release next week.

**Comment by grappler** [comment]
Thanks! @Rarst this is great!

Somehow it is not working for me. I deleted the plugin `searchwp/searchwp-term-highlight` from a project but it still got installed and in the browser I see all of the plugins with the login info below.

I have updated the git repo and ran `composer install`.
`4168fed Fixed display of auth.json with new users option.  (HEAD -> master, origin/master, origin/HEAD) [Andrey Savchenko, 13 hours ago]`

I have the following config.php.
```php
return [
	'users' => [
                'ulrich' => [
                        'hash' => '$2y$10$3i9/lVd8UOFIJ6PAMFt8gu3/r5g0qeCJvoSlLCsvMTythye19F77a',
                        'allow' => [ 'searchwp/searchwp' ],
                        'disallow' => [],
                ],
        ],
];
```

**Comment by Rarst** [comment]
The match is partial, so allowing `searchwp/searchwp` will allow any path with this substring, and so **`searchwp/searchwp`**`-term-highlight`.

Could you please provide your folder tree in full and which permission configuration are you trying to achieve?
