### ISSUE TITLE
Authentification not working

### ISSUE THREAD

**Issue by mawiswiss** [Rarst/release-belt#25]
I'm not able to pass the .htaccess.
Without authentification it's working, but when uncommenting the users part in the `config/config.php` I can't reach the page with the boilerplate snippets anymore.

Any idea what I'm doing wrong?
```
'users'                    => [
        // User login.
        'foousername' => [
            // Provide password hash for HTTP authentication. See bin/encodePassword.php helper.
            'hash'     => '$2y$13$dz7N7JVEyMiDdmbLPqw0he9obf2/poDPLT02BRPHGlPm0UuLZ8kZ6', // test

            // Array of allowed package path matches.
            //'allow'    => ['advanced-custom-fields-pro'],

            // Array of disallowed package path matches.
            //'disallow' => [],
        ],
    ],
```

**Comment by Rarst** [comment]
I am able to login copying this into my config verbatim, so that part is right.

Please double check that you have the current version installed? `0.3` as of writing.

**Comment by mawiswiss** [comment]
I do have. Just cloned the master branch yesterday according to the readme. The log doesn't give any useful errors. I'll setup it again fresh.

**Comment by mawiswiss** [comment]
I just cloned the repo fresh. Copied the sampleConfig.php into config/config.php and uncommented the section at the bottom. I tried to login with the sample data. Sadly it's still not working.

Is there a special package which needs to be installed on the server?

**Comment by Rarst** [comment]
There are no server requirements related to authentication, it is handled completely within PHP load.

1. Might your web server be interfering with it in some way? _Which_ web server do you use and how do you configure it precisely?
2. Had you tried to run it in a different environment, for example locally?

**Comment by mawiswiss** [comment]
It's a shared hosting. Because I can't change the root directory for the subdomain I created an alias which points into SUBDIRECTORY/public folder. It's possible that's there's a issue with that. I'm doing this a lot and haven't had an issue there until this point. The page works without authentification just fine.

I also tried it locally and it's working there. So it's a problem on the server.

**Comment by Rarst** [comment]
Does `/packages.json` work without login?

**Comment by mawiswiss** [comment]
Jep, this works

**Comment by Rarst** [comment]
Then stuff gets routed through `index.php` correctly... Honestly seems like some kind of a hosting conflict, maybe host is explicitly trying to do something when it sees `.htaccess` security request or response. Try asking their support.
