### ISSUE TITLE
Failed to Download

### ISSUE THREAD

**Issue by sebastienserre** [Rarst/release-belt#27]
Hello,
I updated to latest verison of release belt and have now an error on upgrade:
`DownloadinDownloading (failed)
 In RemoteFilesystem.php line 515:
 
   The "/js_composer/js_composer.5.5.5.zip" file could not be downloaded: fail
   ed to open stream: No such file or directory
 `
I have this zip file on my Release/wordpress-plugin directory.
Do you have any idea of what's happened ?

**Comment by Rarst** [comment]
Do you see the package entry correctly in home page?

What do you get if you try to download from home page?

Enabling `debug` in config will show more details.

**Comment by sebastienserre** [comment]
On home page, I can download the zip package.
I've added a config/config.php with
`<?php
declare(strict_types=1);

return [
     'debug'                 => true,
];`
but don't know where I'll received error log. 
I'm running COmposer update inside PhpStorm

**Comment by Rarst** [comment]
Yeah, I think I see the problem, domain is getting omitted from generated links to packages (so it works in home because it's just relative link then).

**Comment by sebastienserre** [comment]
if you need me to test something, let me know

**Comment by Rarst** [comment]
I think I see the problem, I screwed something up moving URL generation to Slim. Will work on a fix later today.

Meanwhile you can downgrade to a previous version, should be no issue with config or anything.

**Comment by sebastienserre** [comment]
what is the cmd to downgrade?

**Comment by Rarst** [comment]
Something like this should do it (if you installed from git):

```bash
git checkout 0.3
composer install --no-dev
```

**Comment by Rarst** [comment]
Released version 0.4.1 with the fix.
