### ISSUE TITLE
Composer installs and creates two directories

### ISSUE THREAD

**Issue by jlauding** [Rarst/release-belt#33]
Ok this might not be a issue with release-belt but I'm not sure.

Composer installs and creates two directories and thus WordPress won't see or list the plugin installed from zip via release belt. 

Example: 
wordpress-plugin/awesome/my-hello-dolly.1.0.0.zip

Composer installs into this path:
plugins/my-hello-dolly/my-hello-dolly/

but should be:
plugins/my-hello-dolly/

Am I missing something?

**Comment by Rarst** [comment]
Do you have installer path customized in your root `composer.json` ? https://github.com/composer/installers#custom-install-paths

Does it happen to every plugin or specific plugin(s)?

**Comment by jlauding** [comment]
Yes I have installer path configured and all other plugins (from wpackagist) gets installed correctly. 

I’ve tried with custom zip installs before trying your tool but I couldn’t get the correct install and now the same problem.

Is this the behavior for zip files with composer or? Can it be some other composer setting maybe. 🤔

**Comment by Rarst** [comment]
Do you have a folder level inside the zip file, and then files in it? Does it match _exactly_ with resulting name of the package?

**Comment by jlauding** [comment]
I have tried with the original zip from the plug-in maker which works in a manual plugin installation with WordPress. So I can’t see anything wrong with the actual zip file.

The plugin doesn’t have a composer file so I also tried adding one to the zip but that didn’t work either.

**Comment by Rarst** [comment]
Really not sure without looking at what actually happens... If possible could you please upload `composer.json` and archive demonstrating the issue? https://www.dropbox.com/request/b7STvaDFXhOt18VoahLX

**Comment by jlauding** [comment]
I've uploaded composer.json. Maybe you can see what's going on. Thanks!

**Comment by Rarst** [comment]
Zip archive of the plugin as well please. :)

**Comment by jlauding** [comment]
Sorry but I can't send that. :-) But this happens with with all zips.

**Comment by jlauding** [comment]
ok @Rarst so I found that the zip contained a folder named __MACOSX
I deleted it and compressed it from the terminal and got it working now.

Thanks for your time looking into this. 👍 
And, good work with Release Belt. 💯

**Comment by jlauding** [comment]
Closing this.
