### ISSUE TITLE
packages.json doesn't get created

### ISSUE THREAD

**Issue by bzx** [Rarst/release-belt#36]
How is this supposed to be created automagically?

**Comment by Rarst** [comment]
Had you followed [installation](https://github.com/Rarst/release-belt#installation) instructions?

Does the home page work?

Note that no _physical_ file is created, the result is generated dynamically. Check `/packages.json` in your browser.

**Comment by bzx** [comment]
Yes, I have followed the installation instructions (also did follow a more [extensive write-up](https://wpahead.com/premium-plugins-composer/)). The home page opens without issue, when I visit /packages.json I get "The requested URL /packages.json was not found on this server."

**Comment by Rarst** [comment]
Ok! Then we got PHP and Belt working, it's probably about link rewrite configuration in server.

Could you please elaborate a bit what is your webserver (e.g. Apache? something else?) and what configuration had you applied?

If you are on a managed host, your hosting support might be in better position to take a look and suggest the configuration to use. :)

**Comment by bzx** [comment]
Oh well, I guess I overlooked the part about Slim configuration... and I had no .htaccess because I assumed one would be there already... sorry. All good now. Closing.
