### ISSUE TITLE
index.php/packages.json" file could not be downloaded: SSL operation failed with code 1

### ISSUE THREAD

**Issue by ant0nioli** [Rarst/release-belt#37]
Once I finished the setup (with authentication and a Let's Encrypt certificate), if I run `composer update` in my local project folder I get this error:
```
 [Composer\Downloader\TransportException]                                                                                                         
  The "https://repo.myurl.tld/index.php/packages.json" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:  
  error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed                                                             
  Failed to enable crypto                                                                                                                          
  failed to open stream: operation failed   
```
I can access to the index.php and to packages.json file via browser

Tried with [this solution](https://stackoverflow.com/questions/24611640/curl-60-ssl-certificate-unable-to-get-local-issuer-certificate) but no luck.

Thank you for this great application!

**Comment by Rarst** [comment]
Belt does literally nothing about SSL, it doesn't care/know if you have it or not, that happens entirely on network level between Composer and your web server.

If the browser doesn't complain about any issues, then likely your PHP runtime on _client_ side (computer you are running Composer from) is trying to use wrong/outdated certificates file or something like that.

**Comment by ant0nioli** [comment]
Thank you Rarst, I'll check in this direction.
