### ISSUE TITLE
Generated package links are not https

### ISSUE THREAD

**Issue by MaximeCulea** [Rarst/release-belt#38]
Hi there, awesome product, thx!

I am facing an issue, the generated links for the packages for each version are not in https.
So when I add the release-belt to my Satis, it not the ability to download the pacakges, resulting in the following error :
```
In Config.php line 453:
                                                                                                                                                                                                   
Your configuration does not allow connections to http://exemple.fr/acf/advanced-custom-fields-pro.5.8.7.zip.
```

Any input? Thx

**Comment by Rarst** [comment]
Can you access Belt home page over https?

Does your repository entry in `composer.json` contain https link to the repository?

**Comment by MaximeCulea** [comment]
I can access to the repo in https, to the /composer.json too and same for /packages.json.
Whilst the generated urls for the packages, in the packages.json are not https :/

**Comment by MaximeCulea** [comment]
I found it by debugging `src/UrlGenerator.php`, the slim scheme was in http, not in https.
My nginx config was missing the `fastcgi_param HTTPS 'on';` cf https://github.com/slimphp/Slim/issues/1861#issuecomment-478331718
