### ISSUE TITLE
Add file upload

### ISSUE THREAD

**Issue by Rarst** [Rarst/release-belt#39]
I was minimal with initial design and this being _exclusively_ for people who know how to FTP things around... Still it's kinda weird that you can't just upload packages from interface.

Would need UI figured out how to smoothly choose type/vendor. Also this potentially drags in the need to _edit_ something that ended up in wrong place.

Would probably be locked to authenticated mode only.

**Comment by Rarst** [comment]
I thought about this some and essentially simplicity of filesystem-centric design translates into challenging UI. Given the need for exact placement/edits I would need to either build entire file manager or a very abstracted taxonomy-like system over underlying file operations.

Not interested in making the effort at the moment.

**Comment by mindfullsilence** [comment]
Could I/my team assist with this? I have a large project right now that will take up my time for the next 3 or 4 weeks - but would be willing to jump into a basic starting point for this project once my schedule clears. I can also check if my UX guy would like to have a crack at creating something easy to navigate.

**Comment by Rarst** [comment]
Still not interested in this as a Belt feature. I don't need it and I don't want to maintain it.

Web upload can also be built _independently_ of Belt, so I am not in the way if anyone wants to. :)
