### ISSUE TITLE
Composer 2.0 Support

### ISSUE THREAD

**Issue by grappler** [Rarst/release-belt#42]
Hi @Rarst 😃 

Have you looked if release-belt is compatible with [Composer 2.0](https://github.com/composer/composer/blob/master/UPGRADE-2.0.md#for-composer-repository-implementors) or if release-belt can profit from the improvements?

**Comment by Rarst** [comment]
Composer 2.0 is perfectly backwards compatible, so there is no issue with it consuming Belt repos.

Belt currently uses the basic flat repository structure, that goes well with its flat file principles. Packagist gets a lot more elaborate with it, but you don't need that unless you are building a repository the _size_ of Packagist.

The new name–based metadata approach seems like it would be relatively easier to build, than old hash-based providers one.

If people start pushing Belt to a limit of flat repo (I don't even practically know where that is, thousands of packages?) working on upgrading is certainly on the table. Hadn't been an issue for anyone (to my knowledge) so far.
