### ISSUE TITLE
Issue to get packages with composer v2

### ISSUE THREAD

**Issue by MaximeCulea** [Rarst/release-belt#44]
Hi, since I updated the project to composer v2, I got all release belt packages that go to 502 :
![release-belt-502 copie](https://user-images.githubusercontent.com/5576409/100555101-a2581a00-3299-11eb-8221-7013b034ef0f.png)
![release-belt-502](https://user-images.githubusercontent.com/5576409/100555103-a5530a80-3299-11eb-9a6a-7f232733d606.png)

This is true on local and client server.

Any idea on this? thx :)

**Comment by Rarst** [comment]
Nothing else changed? PHP install/version on either side?

Does it still work if you downgrade to Composer v1? `composer self-update --1`

Can you download same files with a browser?

**Comment by MaximeCulea** [comment]
Yeah, I had to downgrade to make it work to continue to ship on production.

You are right to ask, the first thing I checked, was to download manually the package that was falling. And it works. 

Moreover, each time I was launching the composer install command, after composer clear cache, it was one of the release belt packages that was falling, but never the same, like random or something like that.

**Comment by Rarst** [comment]
Can you check the server access log to see if it's a genuine 502 failure server-side when it happens?

Also could try logging PHP errors from Belt install.

**Comment by Rarst** [comment]
Also going over the screenshot again the major difference is that Composer v2 uses HTTP2. It's possible that makes _something_ crash, I am not sure that would be _Belt_ specifically (as opposed to web server), but possible.

**Comment by MaximeCulea** [comment]
Thank you for your quick answer @Rarst!

The server is under http2 and I have checked with https://tools.keycdn.com/http2-test. Also, I have tested from "outside" and it's "accessible".

![Bulk-URL-HTTP-Status-Code-Header-Redirect-Checker-httpstatus-io](https://user-images.githubusercontent.com/5576409/100773533-4ad4be00-3401-11eb-94ed-c6485f53f1da.png)

> Also could try logging PHP errors from Belt install.

Is there a way to do so?

**Comment by Rarst** [comment]
> Is there a way to do so?

I would try with regular `php.ini` debug configuration for starters, Belt doesn't do anything special about it (though underlying Slim framework might).

**Comment by MaximeCulea** [comment]
I may found something but not sure what it could lead to `[04-Dec-2020 18:24:28 Europe/Paris] PHP Deprecated:  Use of package root as web root is deprecated in favor of 'public/' directory. in release-belt/index.php on line 10`

**Comment by Rarst** [comment]
Shouldn't be any different functionally, that was just a minor reorganization of Belt files.

**Comment by MaximeCulea** [comment]
@Rarst when you say "that", it refers to an update of release belt?

**Comment by Rarst** [comment]
Yes, that was quite a while ago in Belt 0.2 https://github.com/Rarst/release-belt/blob/master/CHANGELOG.md#02---2018-01-17

**Comment by MaximeCulea** [comment]
Ok this has nothing to do with that, I have installed it in 2019 with 0.5 tag.
Maybe the switch to composer v2 could break something ?

**Comment by Rarst** [comment]
I currently have no guesses what in Belt could break like this. There is nothing in Belt itself that could or would intentionally produce a 502 response, generally that's web server  / network level stuff.

**Comment by Rarst** [comment]
Was there any specific resolution to this, for my information? :)

**Comment by MaximeCulea** [comment]
Nope, finally it is now working now.
On my end, I think there was an issue with one package which was not upgraded to work in composer v2. The hoster told me nothing changed on my server.
So I can't see any other reason.
