### ISSUE TITLE
Support PHP 8

### ISSUE THREAD

**Issue by chesio** [Rarst/release-belt#48]
I've tried to `composer install` Release Belt on PHP 8, but installation failed due to `akrabat/ip-address-middleware` not being PHP 8 compatible in version 1. The package has however version 2 already that does support PHP 8, see: : https://github.com/akrabat/ip-address-middleware/releases

I upgraded locally to version 2 and everything seems to be working fine, so I would suggest to update the dependency as well.

**Comment by Rarst** [comment]
Cheers, bumped this one. Though there are still deprecation notices from older Slim v3, which might need to be silenced if being displayed. A lot more involved to upgrade that one, will make a separate issue.

**Comment by chesio** [comment]
Thanks! I didn't noticed any notices from Slim on my instance, but since I run Release Belt on public server, I likely have them silenced by default. Thanks for the hint though, I'll have a closer look on server logs just in case.
