### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by marekrost** [Rarst/release-belt#52]
Hey,

I just wanted to mention that I love Release belt and I've packaged it for deployment with Docker.

It is based on a minimalistic nginx/php-fpm image. Feel free to take over the repository if you'd like.

https://github.com/marekrost/docker-release-belt
https://hub.docker.com/r/marekrost/release-belt

Best regards
Marek

**Comment by Rarst** [comment]
Cheers, I don't use Docker and have no interest in managing/providing such image, but you are welcome to if there is a need. :)
